server:
  port: 8080

xss:
  # true为启用XSS安全防护
  enabled: true

  # 清理策略
  cleaner:
    # 清理策略名称(唯一标识)
    - cleaner-name: modeXSSCleaner
      # 自定义扩展属性
      property:
        mode: FILTER
        enableEscape: false

  # 过滤器
  filter:
    # 过滤器名称(唯一标识)
    - filter-name: httpRequestMessageXSSHandler
      # 过滤器路径匹配规则, 如果是字符串, 可以通过逗号分割, 定义多个路径匹配规则
      url-patterns: /**
      # 要引用的清理策略名, 如果配置了 cleaner 节点, 优先使用 cleaner节点中的清理策略
      cleaner-ref: modeXSSCleaner
